/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Aries
 */
public class pemesananbarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form permintaanbarang
     */
    ResultSet r;
    Statement s;
    Connection c;
    private Object[][]dataopb=null;
    private String[]label={"No Transaksi OPB","No OPB","Dapartemen","Tanggal OPB"};
    public pemesananbarang() {
        initComponents();
        bukakoneksi();
        comboopb();
        bacaTable();
        notrx();
    }
    private void notrx(){
        try {
           String sql = "select id_ppb from ppb order by id_ppb desc";
           s =c.createStatement();
           r = s.executeQuery(sql);
           if(r.next())
           {
               String noid = r.getString("id_ppb");
               int nomor= Integer.valueOf(noid.substring(5,8));
               if(nomor<9){
                   jtppb.setText("PPB-000"+String.valueOf(nomor+1));
               }else if(nomor<99){
                   jtppb.setText("PPB-00"+String.valueOf(nomor+1));
               }else if(nomor<999){
                   jtppb.setText("PPB-0"+String.valueOf(nomor+1));
               }else{
                   jtppb.setText("PPB-"+String.valueOf(nomor+1));
               }  
           }else{
               jtppb.setText("PPB-0001");
           }
        } catch (Exception e) {
        }
    }
    private void bukakoneksi()
    {
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            c=DriverManager.getConnection("jdbc:mysql://localhost:3306/ta_nita","root","");
            System.out.println("Koneksi Sukses");
        } 
        catch (Exception e) 
        {
            System.out.println("Koneksi Sukses");
        }
    }
    public void comboopb(){
        try 
       {
           String sql = "select id_opb from opb";
           s =c.createStatement();
           r = s.executeQuery(sql);
           while(r.next())
           {
               jcOPB.addItem(r.getString("id_opb"));
           }
           
       }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtppb = new javax.swing.JTextField();
        jjtanggal = new com.toedter.calendar.JDateChooser();
        jbIPB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtket = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcOPB = new javax.swing.JComboBox();
        jbTambah = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtDapart = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPPB = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jbEdit = new javax.swing.JButton();
        jbHapus = new javax.swing.JButton();
        jbCetak = new javax.swing.JButton();
        jbCetak1 = new javax.swing.JButton();
        jtid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Input :: PPB");

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("NO PPB");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Keterangan");

        jbIPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Button-Add-icon.png"))); // NOI18N
        jbIPB.setText("PPB");
        jbIPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIPBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tanggal");

        jtket.setColumns(20);
        jtket.setRows(5);
        jScrollPane2.setViewportView(jtket);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtppb, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jjtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jbIPB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jtppb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jjtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbIPB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("NO OPB");

        jcOPB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "..No OPB.." }));
        jcOPB.setEnabled(false);
        jcOPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcOPBActionPerformed(evt);
            }
        });

        jbTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Button-Add-icon.png"))); // NOI18N
        jbTambah.setText("Tambah");
        jbTambah.setEnabled(false);
        jbTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTambahActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Dapartemen");

        jtDapart.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcOPB, 0, 108, Short.MAX_VALUE)
                    .addComponent(jtDapart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcOPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtDapart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jbTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbPPB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbPPB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbPPBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbPPB);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 629, 170));

        jbEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Actions-document-edit-icon.png"))); // NOI18N
        jbEdit.setText("Edit");
        jbEdit.setEnabled(false);
        jbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditActionPerformed(evt);
            }
        });

        jbHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Actions-edit-delete-icon.png"))); // NOI18N
        jbHapus.setText("Hapus");
        jbHapus.setEnabled(false);
        jbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHapusActionPerformed(evt);
            }
        });

        jbCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer-icon.png"))); // NOI18N
        jbCetak.setText("Cetak IPB");
        jbCetak.setEnabled(false);
        jbCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCetakActionPerformed(evt);
            }
        });

        jbCetak1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Actions-media-playback-start-icon.png"))); // NOI18N
        jbCetak1.setText("Selesai");
        jbCetak1.setEnabled(false);
        jbCetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCetak1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jbEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCetak)
                    .addComponent(jbCetak1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbCetak)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbCetak1)
                        .addComponent(jbEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jtid.setText("jTextField1");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("-");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total OPB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(70, 70, 70))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(9, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void onppb(){
        jtDapart.setEnabled(true);
        jcOPB.setEnabled(true);
        jbCetak.setEnabled(true);
        jbCetak1.setEnabled(true);
        jbEdit.setEnabled(true);
        jbHapus.setEnabled(true);
        jtket.setEnabled(true);
        jbTambah.setEnabled(true);
        
        jbIPB.setEnabled(false);
        jtppb.setEnabled(false);
        jtket.setEnabled(false);
        jjtanggal.setEnabled(false);
    }
    public void ofppb(){
        jtDapart.setEnabled(false);
        jcOPB.setEnabled(false);
        jbCetak.setEnabled(false);
        jbCetak1.setEnabled(false);
        jbEdit.setEnabled(false);
        jtket.setEnabled(false);
        jbHapus.setEnabled(false);
        jbTambah.setEnabled(false);
        
        jbIPB.setEnabled(true);
        jtppb.setEnabled(true);
        jtket.setEnabled(true);
        jjtanggal.setEnabled(true);
    }
    
    public void totalOPB(){
          try 
       {
           String sql = "SELECT COUNT(`id_opb`) AS J FROM `trnsk_opb` WHERE `id_ppb` = '"+jtppb.getText()+"'";
           s =c.createStatement();
           r = s.executeQuery(sql);
           r.next();
           jLabel7.setText(r.getString("J"));
       }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }
    private void jbIPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIPBActionPerformed
        // TODO add your handling code here:
        
        if("".equals(jtppb.getText())){
            JOptionPane.showMessageDialog(null, "Lengkapi dahulu data");
            jtppb.requestFocus();
        }else{
            try {
                s=c.createStatement();
                String a="SELECT * FROM ppb WHERE id_ppb='"+jtppb.getText()+"'";
                r=s.executeQuery(a);
                if(r.next()){
                    JOptionPane.showMessageDialog(null, "OPB Sudah digunakan");
                    jtppb.requestFocus();
                }else{
                    simpanppb();
                    onppb();
                    bacaTable();
                    //comboopb();
                }
                
            } catch (Exception e) {
                
            }
        }
    }//GEN-LAST:event_jbIPBActionPerformed
        private void simpanppb()
    {
        String tanggal ="YYYY-MM-dd";
        SimpleDateFormat format = new SimpleDateFormat(tanggal);
        String tampil = String.valueOf(format.format(jjtanggal.getDate()));
       try 
       {
           String sql = "INSERT INTO ppb VALUES('"+jtppb.getText()+"','"+tampil+"','"+jtket.getText()+"')";
           s.executeUpdate(sql);
           s.close();
           JOptionPane.showMessageDialog(null, "Tambahkan OPB");
       }
       catch (SQLException e) 
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }
    private void hapusdataopb()
  {
      try 
      {
          String sql = "DELETE FROM trnsk_opb WHERE id_transkopb="+Integer.valueOf(jtid.getText())+"";
          s.executeUpdate(sql);
          s.close();
          JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
          
      } 
      catch (SQLException e)
      {
          JOptionPane.showMessageDialog(null, e);
      }
  }
     private void editdataopb()
    {
      try 
      {
          String sql= "UPDATE trnsk_opb SET id_opb='"+jcOPB.getSelectedItem()+"', id_ppb='"+jtppb.getText()+"' "
                  + "WHERE id_transkopb="+Integer.valueOf(jtid.getText())+"";
          s.executeUpdate(sql);
          s.close();
          JOptionPane.showMessageDialog(null, "Data berhasil di Edit");
          
      }
      catch (SQLException e) 
      {
          JOptionPane.showMessageDialog(null, e);
      }
    }
     private void simpanopb()
    {
       try 
       {
           String sql = "INSERT INTO trnsk_opb VALUES(NULL,'"+jcOPB.getSelectedItem()+"', '"+jtppb.getText()+"')";
           s.executeUpdate(sql);
           s.close();
           JOptionPane.showMessageDialog(null, "OPB Berhasil ditambah");
           
       }
       catch (SQLException e) 
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }
    public void resetopb(){
        jcOPB.setSelectedIndex(0);
        jtDapart.setText("");
        jtket.setText("");
    }
    private void jcOPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcOPBActionPerformed
        // TODO add your handling code here:
        int i = jcOPB.getSelectedIndex();
        if (i== 0){
            jtDapart.setText("");
            return;
        }else{
            
        try 
       {
           String sql = "SELECT d.nama_dapartement, o.Keterangan FROM dapartemen AS d, opb AS o "
                   + "WHERE o.id_dapartement = d.id_dapartement AND o.id_opb='"+jcOPB.getSelectedItem()+"'";
           s =c.createStatement();
           r = s.executeQuery(sql);
           r.next();
               this.jtDapart.setText(r.getString("nama_dapartement"));
               this.jtket.setText(r.getString("Keterangan"));
           
       }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
        }
    }//GEN-LAST:event_jcOPBActionPerformed

    private void jtbPPBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbPPBMouseClicked
        // TODO add your handling code here:
        settable();
    }//GEN-LAST:event_jtbPPBMouseClicked

    private void jbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTambahActionPerformed
        // TODO add your handling code here:
        if("..No OPB..".equals(jcOPB.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Lengkapi dahulu data");
            jcOPB.requestFocus();
        }
        else{
            try {
                s=c.createStatement();
                String a="SELECT * FROM trnsk_opb WHERE id_opb ='"+jcOPB.getSelectedItem()+"' "
                        + "AND id_ppb ='"+jtppb.getText()+"'";
                r=s.executeQuery(a);
                if(r.next()){
                    JOptionPane.showMessageDialog(null, "Nomor OPB Sudah digunakan");
                    jcOPB.requestFocus();
                }
                else{
                    simpanopb();
                    resetopb();
                    bacaTable();
                    totalOPB();
                }
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_jbTambahActionPerformed

    private void jbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditActionPerformed
        // TODO add your handling code here:
        if("..No OPB..".equals(jcOPB.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Lengkapi dahulu data");
            jcOPB.requestFocus();
        }
        else{
            editdataopb();
            resetopb();
            bacaTable();
        }
    }//GEN-LAST:event_jbEditActionPerformed

    private void jbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHapusActionPerformed
        // TODO add your handling code here:
        if("..No OPB..".equals(jcOPB.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Lengkapi dahulu data");
            jcOPB.requestFocus();
        }
        else{
            hapusdataopb();
            resetopb();
            bacaTable();
        }
    }//GEN-LAST:event_jbHapusActionPerformed
    private static String path = System.getProperty("user.dir")+"/src/Laporan/";
    private void jbCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCetakActionPerformed
        // TODO add your handling code here:
        String filename = path+"LaporanIPB_1.jrxml";
        JasperReport jasrep;
        JasperPrint japri;
        JasperViewer javie = null;
        HashMap param = new HashMap(1);
        JasperDesign jasdes;
        try {
            param.put("ppb",jtppb.getText());
            File report = new File(filename);
            jasdes = JRXmlLoader.load(report);
            jasrep = JasperCompileManager.compileReport(jasdes);
            japri = JasperFillManager.fillReport(jasrep,param,Komponen.koneksi.GetConnection());
            javie.viewReport(japri,false);
        } catch (Exception e) {
            System.out.print("gagal ngprint");
        }
        
    }//GEN-LAST:event_jbCetakActionPerformed

    private void jbCetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCetak1ActionPerformed
        // TODO add your handling code here:
        ofppb();
        jtket.setText("");
        notrx();
    }//GEN-LAST:event_jbCetak1ActionPerformed
    public void bacaTable(){
        try 
       {
           s=c.createStatement();
           String sql = "SELECT tr.id_transkopb, tr.id_opb, d.nama_dapartement, o.tanggal FROM "
                   + "trnsk_opb AS tr, dapartemen AS d, opb AS o WHERE tr.id_opb = o.id_opb "
                   + "AND o.id_dapartement = d.id_dapartement AND tr.id_ppb ='"+jtppb.getText()+"'";
           r=s.executeQuery(sql);
           ResultSetMetaData m=r.getMetaData();
           int kolom=m.getColumnCount();
           int baris=0;
           while(r.next())
           {
               baris = r.getRow();
           }
           dataopb= new Object[baris][kolom];
           int x=0;
           r.beforeFirst();
           while(r.next())
           {
               dataopb[x][0]=r.getString("id_transkopb");
               dataopb[x][1]=r.getString("id_opb");
               dataopb[x][2]=r.getString("nama_dapartement");
               dataopb[x][3]=r.getString("tanggal");
               x++;
           }
           jtbPPB.setModel(new DefaultTableModel(dataopb, label));
       }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }
     private void settable()
   {
       int row = jtbPPB.getSelectedRow();
       jtid.setText((String)jtbPPB.getValueAt(row, 0));
       jcOPB.setSelectedItem((String)jtbPPB.getValueAt(row, 1));
       jtDapart.setText((String)jtbPPB.getValueAt(row, 2));
       jcOPB.requestFocus();
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCetak;
    private javax.swing.JButton jbCetak1;
    private javax.swing.JButton jbEdit;
    private javax.swing.JButton jbHapus;
    private javax.swing.JButton jbIPB;
    private javax.swing.JButton jbTambah;
    private javax.swing.JComboBox jcOPB;
    private com.toedter.calendar.JDateChooser jjtanggal;
    private javax.swing.JTextField jtDapart;
    private javax.swing.JTable jtbPPB;
    private javax.swing.JTextField jtid;
    private javax.swing.JTextArea jtket;
    private javax.swing.JTextField jtppb;
    // End of variables declaration//GEN-END:variables
}
