/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aries
 */
public class permintaanbarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form permintaanbarang
     */
    ResultSet r;
    Statement s;
    Connection c;
    private Object[][]databarang=null;
    private String[]label={"No Transaksi Barang","ID Barang","Nama Barang","Spesifikasi","Jumlah Barang"};
    public permintaanbarang() {
        initComponents();
        bukakoneksi();
        combobarang();
        combodapart();
        bacaTable();
        notrx();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtopb = new javax.swing.JTextField();
        jjtanggal = new com.toedter.calendar.JDateChooser();
        jbopb = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcIddapart = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jtDpart = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtket = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtjumlah = new javax.swing.JTextField();
        jcbarang = new javax.swing.JComboBox();
        jbtambah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtnamabarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtspek = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbopb = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jbedit = new javax.swing.JButton();
        jbhapus = new javax.swing.JButton();
        jbselesai = new javax.swing.JButton();
        jtid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Input :: OPB");

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("NO OPB");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tanggal");

        jbopb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Button-Add-icon.png"))); // NOI18N
        jbopb.setText("OPB");
        jbopb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbopbActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ID Dapartement");

        jcIddapart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".....Masukan ID....." }));
        jcIddapart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcIddapartActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Dapartement");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Keterangan");

        jtket.setColumns(20);
        jtket.setRows(5);
        jScrollPane2.setViewportView(jtket);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcIddapart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jjtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtopb, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                    .addComponent(jtDpart))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbopb, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtopb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jjtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcIddapart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtDpart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jbopb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ID Barang");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Jumlah Barang");

        jtjumlah.setEnabled(false);

        jcbarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...Masukan ID..." }));
        jcbarang.setEnabled(false);
        jcbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbarangActionPerformed(evt);
            }
        });

        jbtambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Button-Add-icon.png"))); // NOI18N
        jbtambah.setText("Tambah");
        jbtambah.setEnabled(false);
        jbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtambahActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nama Barang");

        jtnamabarang.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Spesifikasi");

        jtspek.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtnamabarang)
                    .addComponent(jtjumlah, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtspek))
                .addGap(18, 18, 18)
                .addComponent(jbtambah, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtambah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtspek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jtbopb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbopb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbopbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbopb);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        jbedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Actions-document-edit-icon.png"))); // NOI18N
        jbedit.setText("Edit");
        jbedit.setEnabled(false);
        jbedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeditActionPerformed(evt);
            }
        });

        jbhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Actions-edit-delete-icon.png"))); // NOI18N
        jbhapus.setText("Hapus");
        jbhapus.setEnabled(false);
        jbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhapusActionPerformed(evt);
            }
        });

        jbselesai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Actions-media-playback-start-icon.png"))); // NOI18N
        jbselesai.setText("Selesai");
        jbselesai.setEnabled(false);
        jbselesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbselesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbedit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbselesai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbselesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtid.setText("jTextField1");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Total Barang");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("_");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(485, 485, 485)
                        .addComponent(jLabel10)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jtid, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void bukakoneksi()
    {
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            c=DriverManager.getConnection("jdbc:mysql://localhost:3306/ta_nita","root","");
            System.out.println("Koneksi Sukses");
        } 
        catch (Exception e) 
        {
            System.out.println("Koneksi Sukses");
        }
    }
    public void notrx(){
        try {
           String sql12 = "select * from opb order by id_opb desc";
           s =c.createStatement();
           r = s.executeQuery(sql12);
           if(r.next())
           {
               String noid = r.getString("id_opb");
               int nomor= Integer.valueOf(noid.substring(5,8));
               if(nomor<9){
                   jtopb.setText("OPB-000"+String.valueOf(nomor+1));
               }else if(nomor<99){
                   jtopb.setText("OPB-00"+String.valueOf(nomor+1));
               }else if(nomor<999){
                   jtopb.setText("OPB-0"+String.valueOf(nomor+1));
               }else{
                   jtopb.setText("OPB-"+String.valueOf(nomor+1));
               }  
           }else{
               jtopb.setText("OPB-0001");
           }
        } catch (Exception e) {
        }
    }
    public void totalbrg(){
          try 
       {
           String sql = "SELECT SUM(`jumlah`) as J FROM `transk_barang` WHERE `id_opb` ='"+jtopb.getText()+"'";
           s =c.createStatement();
           r = s.executeQuery(sql);
           r.next();
           jLabel11.setText(r.getString("J"));
       }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }
    public void combobarang(){
        try 
       {
           String sql = "select id_barang from barang";
           s =c.createStatement();
           r = s.executeQuery(sql);
           while(r.next())
           {
               jcbarang.addItem(r.getString("id_barang"));
           }
           
       }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }
    public void bacaTable(){
        try 
       {
           s=c.createStatement();
           String sql = "SELECT tb.id_transk, tb.id_barang, b.nama_barang, b.Spesifikasi, tb.jumlah FROM barang "
                   + "AS b, transk_barang AS tb, opb AS o WHERE tb.id_barang = b.id_barang "
                   + "AND tb.id_opb = o.id_opb AND tb.id_opb ='"+jtopb.getText()+"'";
           r=s.executeQuery(sql);
           ResultSetMetaData m=r.getMetaData();
           int kolom=m.getColumnCount();
           int baris=0;
           while(r.next())
           {
               baris = r.getRow();
           }
           databarang= new Object[baris][kolom];
           int x=0;
           r.beforeFirst();
           while(r.next())
           {
               databarang[x][0]=r.getString("id_transk");
               databarang[x][1]=r.getString("id_barang");
               databarang[x][2]=r.getString("nama_barang");
               databarang[x][3]=r.getString("Spesifikasi");
               databarang[x][4]=r.getString("jumlah");
               x++;
           }
           jtbopb.setModel(new DefaultTableModel(databarang, label));
       }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }
     private void settable()
   {
       int row = jtbopb.getSelectedRow();
       jtid.setText((String)jtbopb.getValueAt(row, 0));
       jcbarang.setSelectedItem((String)jtbopb.getValueAt(row, 1));
       jtjumlah.setText((String)jtbopb.getValueAt(row, 4));
        jtspek.setText((String)jtbopb.getValueAt(row, 3));
       jtbopb.requestFocus();
   }
    public void combodapart(){
        try 
       {
           String sql = "select id_dapartement from dapartemen";
           s =c.createStatement();
           r = s.executeQuery(sql);
           while(r.next())
           {
               jcIddapart.addItem(r.getString("id_dapartement"));
           }
           
       }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }
     private void simpanOpb()
    {
        String tanggal ="YYYY-MM-dd";
        SimpleDateFormat format = new SimpleDateFormat(tanggal);
        String tampil = String.valueOf(format.format(jjtanggal.getDate()));
       try 
       {
           String sql = "INSERT INTO opb VALUES('"+jtopb.getText()+"','"+jcIddapart.getSelectedItem()+"','"+tampil+"','"+jtket.getText()+"')";
           s.executeUpdate(sql);
           s.close();
           JOptionPane.showMessageDialog(null, "Tambahkan Barang");
       }
       catch (SQLException e) 
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }
     private void hapusdata()
  {
      try 
      {
          String sql = "DELETE FROM transk_barang WHERE id_transk="+Integer.valueOf(jtid.getText())+"";
          s.executeUpdate(sql);
          s.close();
          JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
          bacaTable();
          resetbarang();
      } 
      catch (SQLException e)
      {
          JOptionPane.showMessageDialog(null, e);
      }
  }
     private void editdata()
    {
      try 
      {
          String sql= "UPDATE transk_barang SET id_barang='"+jcbarang.getSelectedItem()+"', "
                  + "jumlah="+Integer.valueOf(jtjumlah.getText())+" WHERE "
                  + "id_transk="+Integer.valueOf(jtid.getText())+"";
          s.executeUpdate(sql);
          s.close();
          JOptionPane.showMessageDialog(null, "Data berhasil di Edit");
          bacaTable();
          resetbarang();
      }
      catch (SQLException e) 
      {
          JOptionPane.showMessageDialog(null, e);
      }
    }
     private void simpanbrg()
    {
       try 
       {
           String sql = "INSERT INTO transk_barang VALUES(NULL,'"+jcbarang.getSelectedItem()+"',"
                   + "'"+jtopb.getText()+"',"+Integer.valueOf(jtjumlah.getText())+")";
           s.executeUpdate(sql);
           s.close();
           JOptionPane.showMessageDialog(null, "Barang Berhasil ditambah");
           bacaTable();
       }
       catch (SQLException e) 
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }
    private void jcIddapartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcIddapartActionPerformed
        // TODO add your handling code here:
        int i = jcIddapart.getSelectedIndex();
        if (i== 0){
            jtDpart.setText("");
            return;
        }else{
        try 
       {
           String sql = "select nama_dapartement from dapartemen WHERE id_dapartement ='"+jcIddapart.getSelectedItem()+"'";
           s =c.createStatement();
           r = s.executeQuery(sql);
           r.next();
               this.jtDpart.setText(r.getString("nama_dapartement"));
           
       }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
        }
    }//GEN-LAST:event_jcIddapartActionPerformed

    private void jcbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbarangActionPerformed
        // TODO add your handling code here:
        int i = jcbarang.getSelectedIndex();
        if (i== 0){
            jtnamabarang.setText("");
            return;
        }else{
        try 
       {
           String sql = "select * from barang WHERE id_barang ='"+jcbarang.getSelectedItem()+"'";
           s =c.createStatement();
           r = s.executeQuery(sql);
           r.next();
               this.jtnamabarang.setText(r.getString("nama_barang"));
               this.jtspek.setText(r.getString("Spesifikasi"));
           
       }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
        }
    }//GEN-LAST:event_jcbarangActionPerformed

    private void jbopbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbopbActionPerformed
        // TODO add your handling code here:
        
        if("".equals(jtopb.getText()) || ".....Masukan ID.....".equals(jcIddapart.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Lengkapi dahulu data");
            jtopb.requestFocus();
        }else{
            try {
                s=c.createStatement();
                String a="SELECT * FROM opb WHERE id_opb='"+jtopb.getText()+"'";
                r=s.executeQuery(a);
                if(r.next()){
                    JOptionPane.showMessageDialog(null, "OPB Sudah digunakan");
                    jtopb.requestFocus();
                }else{
                    simpanOpb();
                    jtopb.setEnabled(false);
                    jbopb.setEnabled(false);
                    jtDpart.setEnabled(false);
                    jtspek.setEnabled(true);
                    jcIddapart.setEnabled(false);
                    jtket.setEnabled(false);
                    jjtanggal.setEnabled(false);
                    jcbarang.setEnabled(true);
                    jtnamabarang.setEnabled(true);
                    jtjumlah.setEnabled(true);
                    jbselesai.setEnabled(true);
                    jbtambah.setEnabled(true);
                    jbedit.setEnabled(true);
                    jbhapus.setEnabled(true);
                    //combobarang();
                    //combodapart();
                    bacaTable();
                }
            } catch (Exception e) {
            }
        }
            
    }//GEN-LAST:event_jbopbActionPerformed

    private void jbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtambahActionPerformed
        // TODO add your handling code here:
        if("".equals(jtjumlah.getText()) || "...Masukan ID...".equals(jcbarang.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Lengkapi dahulu data");
            jtopb.requestFocus();
        }
        else{
            try {
                s=c.createStatement();
                String a="SELECT * FROM transk_barang WHERE id_opb ='"+jtopb.getText()+"' "
                        + "AND id_barang ='"+jcbarang.getSelectedItem()+"'";
                r=s.executeQuery(a);
                if(r.next()){
                    JOptionPane.showMessageDialog(null, "ID Barang Sudah Ditambahkan");
                    jtopb.requestFocus();
                }else{
                    simpanbrg();
                    resetbarang();
                    totalbrg();
                }
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_jbtambahActionPerformed

    private void jtbopbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbopbMouseClicked
        // TODO add your handling code here:
        settable();
    }//GEN-LAST:event_jtbopbMouseClicked

    private void jbeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeditActionPerformed
        // TODO add your handling code here:
        if("".equals(jtjumlah.getText()) || "...Masukan ID...".equals(jcbarang.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Lengkapi dahulu data");
            jtopb.requestFocus();
        }
        else{
            if(JOptionPane.showConfirmDialog(null, "apakah data ini ingin di Edit ?", "peringatan",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.OK_OPTION)
            {
            editdata();
            }
        }
    }//GEN-LAST:event_jbeditActionPerformed

    private void jbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhapusActionPerformed
        // TODO add your handling code here:
        if("".equals(jtjumlah.getText()) || "...Masukan ID...".equals(jcbarang.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Lengkapi dahulu data");
            jtopb.requestFocus();
        }
        else{
            if(JOptionPane.showConfirmDialog(null, "apakah data ini ingin di Edit ?", "peringatan",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.OK_OPTION)
            {
            hapusdata();
            }
        }
    }//GEN-LAST:event_jbhapusActionPerformed
    
    private void jbselesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbselesaiActionPerformed
        // TODO add your handling code here:
                    jLabel11.setText("-");
                    jtopb.setEnabled(true);
                    jbopb.setEnabled(true);
                    jtopb.setText("");
                    jtket.setText("");
                    jtket.setEnabled(true);
                    jcIddapart.setSelectedIndex(0);
                    jtDpart.setEnabled(true);
                    jcIddapart.setEnabled(true);
                    jjtanggal.setEnabled(true);
                    
                    jcbarang.setEnabled(false);
                    jtnamabarang.setEnabled(false);
                    jtjumlah.setEnabled(false);
                    jbselesai.setEnabled(false);
                    jbtambah.setEnabled(false);
                    jbedit.setEnabled(false);
                    jbhapus.setEnabled(false);
                    bacaTable();
                    resetbarang();
                    notrx();
    }//GEN-LAST:event_jbselesaiActionPerformed
    public void resetbarang(){
        jcbarang.setSelectedIndex(0);
        jtjumlah.setText("");
        jtspek.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbedit;
    private javax.swing.JButton jbhapus;
    private javax.swing.JButton jbopb;
    private javax.swing.JButton jbselesai;
    private javax.swing.JButton jbtambah;
    private javax.swing.JComboBox jcIddapart;
    private javax.swing.JComboBox jcbarang;
    private com.toedter.calendar.JDateChooser jjtanggal;
    private javax.swing.JTextField jtDpart;
    private javax.swing.JTable jtbopb;
    private javax.swing.JTextField jtid;
    private javax.swing.JTextField jtjumlah;
    private javax.swing.JTextArea jtket;
    private javax.swing.JTextField jtnamabarang;
    private javax.swing.JTextField jtopb;
    private javax.swing.JTextField jtspek;
    // End of variables declaration//GEN-END:variables
}
